### PR TITLE
Add script for temp bug fix to Dec schedules

### PR DESCRIPTION
**Pull request by tsuriga**
Edit user credentials in fix_schedules_dec20.php and run it. Assumes that PDO and MySQL connection for it are supported. As for the second script I understood one could just dump the database and revert changes on Dec 28th since there are no changes to be made to it during that one week period - I included a bash script for that.

### CODE REVIEW

**Comment by leandrolages** [comment]
Hi,

Both scripts should be done in PHP :) And here I have only a backup of the table, there is no commando to restore. Ok, I know how to use mysql and perfectly should restore it but the purpose of the exercise is to create both scripts in true PHP.

Can you try please create the second one? I will check right now the first one.

Thanks

**Comment by leandrolages** [comment]
Just checked your test. I still didn't focus on the design of your solution and code standards. I am focusing in this comment if your script is correct.

1 - In your opinion, how can I define that a restaurant is closed in the vendor_schedule table? (Hint: Monday is a closed day).

2 - Based on your answer above, do you think your solution is right? If the answer is NO, can you send another pull request with the right solution? If YES, just send me a pull request with the second script :)

**Comment by tsuriga** [comment]
Right, so the sunday's original NULL entry got me. I added a command-line option for the fixer script for restoration, either -r or --restore (it assumes the fix has been applied before). If all this were to go and exist alongside other code in a repository I'd perhaps namespace all of them into a DecBugFix namespace of their own so that they're easily distinguishable from normal everyday code.

**Comment by tsuriga** [comment]
1. So I originally thought the null entry would signify a closed date but now I changed it so that there's no weekday entry for a vendor if the restaurant is closed that day.

**Pull request closed without merging**
